export const Commands = {
	WEBVIEW_READY: 'webviewReady',
	SEND_REQUEST: 'sendRequest',
	START_OAUTH2_AUTHORIZATION: 'startOAuth2Authorization',
	EXCHANGE_OAUTH2_CODE: 'exchangeOAuth2Code',
	GENERATE_OAUTH2_TOKEN: 'generateOAuth2Token',
	REQUEST_DEVICE_CODE: 'requestDeviceCode',
	FORM_DATA_FILE_REQUEST: 'formDataFileRequest',
	BINARY_FILE_REQUEST: 'binaryFileRequest',
	OPEN_FILE_IN_EDITOR: 'openFileInEditor',
	CREATE_COLLECTION: 'createCollection',
	SAVE_REQUEST: 'saveRequest',
	UPDATE_COLLECTION: 'updateCollection',
	DELETE_COLLECTION: 'deleteCollection',
	DELETE_REQUEST: 'deleteRequest',
	UPDATE_REQUEST: 'updateRequest',
	REORDER_REQUESTS: 'reorderRequests',
	CREATE_ENVIRONMENT: 'createEnvironment',
	DELETE_ENVIRONMENT: 'deleteEnvironment',
	SET_ACTIVE_ENVIRONMENT: 'setActiveEnvironment',
	CLEAR_HISTORY: 'clearHistory',
	DELETE_HISTORY_ITEM: 'deleteHistoryItem',
};
