// Common HTTP header names for autocomplete suggestions
export const COMMON_HEADER_NAMES: Record<'value' | 'label', string>[] = [
	{ value: 'Accept', label: 'Accept' },
	{ value: 'Accept-Encoding', label: 'Accept-Encoding' },
	{ value: 'Accept-Language', label: 'Accept-Language' },
	{ value: 'Authorization', label: 'Authorization' },
	{ value: 'Cache-Control', label: 'Cache-Control' },
	{ value: 'Connection', label: 'Connection' },
	{ value: 'Content-Length', label: 'Content-Length' },
	{ value: 'Content-Type', label: 'Content-Type' },
	{ value: 'Cookie', label: 'Cookie' },
	{ value: 'Date', label: 'Date' },
	{ value: 'Host', label: 'Host' },
	{ value: 'Origin', label: 'Origin' },
	{ value: 'Pragma', label: 'Pragma' },
	{ value: 'Referer', label: 'Referer' },
	{ value: 'User-Agent', label: 'User-Agent' },
	{ value: 'X-Requested-With', label: 'X-Requested-With' },
	{ value: 'X-Forwarded-For', label: 'X-Forwarded-For' },
	{ value: 'X-Frame-Options', label: 'X-Frame-Options' },
	{ value: 'X-XSS-Protection', label: 'X-XSS-Protection' },
	{ value: 'X-Content-Type-Options', label: 'X-Content-Type-Options' },
	{ value: 'If-Modified-Since', label: 'If-Modified-Since' },
	{ value: 'If-None-Match', label: 'If-None-Match' },
	{ value: 'ETag', label: 'ETag' },
	{ value: 'Expires', label: 'Expires' },
	{ value: 'Location', label: 'Location' },
	{ value: 'Set-Cookie', label: 'Set-Cookie' },
	{ value: 'Upgrade-Insecure-Requests', label: 'Upgrade-Insecure-Requests' },
	{ value: 'Access-Control-Allow-Origin', label: 'Access-Control-Allow-Origin' },
	{ value: 'Access-Control-Allow-Headers', label: 'Access-Control-Allow-Headers' },
	{ value: 'Access-Control-Allow-Methods', label: 'Access-Control-Allow-Methods' },
	{ value: 'Access-Control-Expose-Headers', label: 'Access-Control-Expose-Headers' },
	{ value: 'Access-Control-Max-Age', label: 'Access-Control-Max-Age' },
	{ value: 'Access-Control-Request-Headers', label: 'Access-Control-Request-Headers' },
	{ value: 'Access-Control-Request-Method', label: 'Access-Control-Request-Method' },
];
