// src/constants/header-default-values.ts
// Common default values for popular HTTP headers, for use in autocomplete value suggestions

export const HEADER_DEFAULT_VALUES: Record<string, { label: string; value: string }[]> = {
	Accept: [
		{ label: 'application/json', value: 'application/json' },
		{ label: 'application/xml', value: 'application/xml' },
		{ label: 'application/xhtml+xml', value: 'application/xhtml+xml' },
		{ label: 'application/javascript', value: 'application/javascript' },
		{ label: 'application/pdf', value: 'application/pdf' },
		{ label: 'application/zip', value: 'application/zip' },
		{ label: 'application/gzip', value: 'application/gzip' },
		{ label: 'application/msword', value: 'application/msword' },
		{
			label: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			value: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		},
		{ label: 'application/vnd.ms-excel', value: 'application/vnd.ms-excel' },
		{ label: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', value: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
		{ label: 'application/vnd.ms-powerpoint', value: 'application/vnd.ms-powerpoint' },
		{
			label: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
			value: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
		},
		{ label: 'application/ld+json', value: 'application/ld+json' },
		{ label: 'application/geo+json', value: 'application/geo+json' },
		{ label: 'application/x-www-form-urlencoded', value: 'application/x-www-form-urlencoded' },
		{ label: 'application/x-ndjson', value: 'application/x-ndjson' },
		{ label: 'application/x-yaml', value: 'application/x-yaml' },
		{ label: 'image/png', value: 'image/png' },
		{ label: 'image/jpeg', value: 'image/jpeg' },
		{ label: 'image/gif', value: 'image/gif' },
		{ label: 'image/webp', value: 'image/webp' },
		{ label: 'image/svg+xml', value: 'image/svg+xml' },
		{ label: 'text/plain', value: 'text/plain' },
		{ label: 'text/html', value: 'text/html' },
		{ label: 'text/css', value: 'text/css' },
		{ label: 'text/csv', value: 'text/csv' },
		{ label: 'text/xml', value: 'text/xml' },
		{ label: 'text/markdown', value: 'text/markdown' },
		{ label: 'audio/mpeg', value: 'audio/mpeg' },
		{ label: 'audio/ogg', value: 'audio/ogg' },
		{ label: 'video/mp4', value: 'video/mp4' },
		{ label: 'video/webm', value: 'video/webm' },
		{ label: 'multipart/form-data', value: 'multipart/form-data' },
		{ label: '*/*', value: '*/*' },
	],
	'Content-Type': [
		{ label: 'application/json', value: 'application/json' },
		{ label: 'application/xml', value: 'application/xml' },
		{ label: 'application/xhtml+xml', value: 'application/xhtml+xml' },
		{ label: 'application/javascript', value: 'application/javascript' },
		{ label: 'application/pdf', value: 'application/pdf' },
		{ label: 'application/zip', value: 'application/zip' },
		{ label: 'application/gzip', value: 'application/gzip' },
		{ label: 'application/msword', value: 'application/msword' },
		{
			label: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			value: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		},
		{ label: 'application/vnd.ms-excel', value: 'application/vnd.ms-excel' },
		{ label: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', value: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
		{ label: 'application/vnd.ms-powerpoint', value: 'application/vnd.ms-powerpoint' },
		{
			label: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
			value: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
		},
		{ label: 'application/ld+json', value: 'application/ld+json' },
		{ label: 'application/geo+json', value: 'application/geo+json' },
		{ label: 'application/x-www-form-urlencoded', value: 'application/x-www-form-urlencoded' },
		{ label: 'application/x-ndjson', value: 'application/x-ndjson' },
		{ label: 'application/x-yaml', value: 'application/x-yaml' },
		{ label: 'image/png', value: 'image/png' },
		{ label: 'image/jpeg', value: 'image/jpeg' },
		{ label: 'image/gif', value: 'image/gif' },
		{ label: 'image/webp', value: 'image/webp' },
		{ label: 'image/svg+xml', value: 'image/svg+xml' },
		{ label: 'text/plain', value: 'text/plain' },
		{ label: 'text/html', value: 'text/html' },
		{ label: 'text/css', value: 'text/css' },
		{ label: 'text/csv', value: 'text/csv' },
		{ label: 'text/xml', value: 'text/xml' },
		{ label: 'text/markdown', value: 'text/markdown' },
		{ label: 'audio/mpeg', value: 'audio/mpeg' },
		{ label: 'audio/ogg', value: 'audio/ogg' },
		{ label: 'video/mp4', value: 'video/mp4' },
		{ label: 'video/webm', value: 'video/webm' },
		{ label: 'multipart/form-data', value: 'multipart/form-data' },
	],
	'Accept-Encoding': [
		{ label: 'gzip', value: 'gzip' },
		{ label: 'deflate', value: 'deflate' },
		{ label: 'br', value: 'br' },
	],
	'Accept-Language': [
		{ label: 'en-US', value: 'en-US' },
		{ label: 'en', value: 'en' },
		{ label: 'fr', value: 'fr' },
		{ label: 'de', value: 'de' },
	],
	'Cache-Control': [
		{ label: 'no-cache', value: 'no-cache' },
		{ label: 'no-store', value: 'no-store' },
		{ label: 'max-age=0', value: 'max-age=0' },
	],
	Connection: [
		{ label: 'keep-alive', value: 'keep-alive' },
		{ label: 'close', value: 'close' },
	],
	Pragma: [{ label: 'no-cache', value: 'no-cache' }],
};
